export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[var(--background)] text-[var(--foreground)] px-4 py-12 sm:px-8">
      <div className="mx-auto max-w-4xl space-y-8">
        <header className="space-y-2">
          <h1 className="text-3xl font-semibold">Privacy & Terms</h1>
          <p className="text-sm text-[color-mix(in_srgb,var(--foreground)_70%,transparent)]">
            Last updated: October 17, 2025
          </p>
        </header>

        <section className="prose max-w-none text-sm text-[color-mix(in_srgb,var(--foreground)_80%,transparent)] space-y-6">
          <h2 className="mt-2 font-semibold">Who we are</h2>
          <p className="mt-1">
            This application, &quot;Academia Agent&quot;, is owned, developed, and operated by Eight Twelve Consulting LLC
            (&quot;Eight Twelve Consulting&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). Our mission is to help students, families, and educational
            staff explore post-secondary programs and plan for higher-education journeys.
          </p>

          <h2 className="mt-4 font-semibold">Information we collect</h2>
          <p className="mt-1">
            We collect the information you provide when you sign in or use the application. This may include your
            name, email address, and any profile information returned by your chosen federated sign-in provider
            (for example: Google, Apple, Microsoft, or Amazon). We also collect the content of the messages you
            send to the Academia Agent during chat sessions to fulfill your requests.
          </p>

          <h2 className="mt-4 font-semibold">How we use your email address</h2>
          <p className="mt-1">
            If you provide an email address as part of sign-up or authentication, Eight Twelve Consulting LLC will
            store that email and may use it to send marketing communications about Academia Agent, related services,
            updates, or events. By using the application and providing your email, you consent to receive these
            marketing messages. You can opt out of marketing communications at any time by following the unsubscribe
            link included in those messages or by contacting us directly (see the &quot;Contact&quot; section below).
          </p>

          <h2 className="mt-4 font-semibold">Storage and security</h2>
          <p className="mt-1">
            We store user account metadata and marketing consent in our backend systems. The application uses AWS
            services (for example: Cognito, AppSync, DynamoDB, and Bedrock AgentCore) to authenticate users and
            process requests. We take commercially reasonable measures to protect personal data in transit and at rest,
            but no internet transmission or storage mechanism can be guaranteed to be 100% secure.
          </p>

          <h2 className="mt-4 font-semibold">Sharing and disclosure</h2>
          <p className="mt-1">
            We will not sell your personal information. We may share aggregated or de-identified analytics data with
            partners. We may also disclose personal information if required by law or to protect our rights.
          </p>

          <h2 className="mt-4 font-semibold">Your choices and rights</h2>
          <p className="mt-1">
            You may request access to, correction of, or deletion of your personal data by contacting us at the
            address below. If you wish to opt out of marketing communications, use the unsubscribe link in any
            marketing email or contact us directly.
          </p>

          <h2 className="mt-4 font-semibold">Disclaimer</h2>
          <p className="mt-1">
            Information provided by Academia Agent is for informational purposes only and does not constitute
            professional advice. While we strive to provide accurate and helpful information, our recommendations
            are generated by AI models and may be incomplete, out of date, or otherwise incorrect. You are solely
            responsible for verifying any information before acting on it. Eight Twelve Consulting LLC and its
            affiliates, partners, and service providers are not liable for any decisions made based on the
            information provided through this application.
          </p>

          <h2 className="mt-4 font-semibold">Changes to this policy</h2>
          <p className="mt-1">
            We may update this Privacy & Terms page from time to time. When we make material changes, we will provide
            notice through the application or via email to the address you provided.
          </p>

          <h2 className="mt-4 font-semibold">Contact</h2>
          <p className="mt-1">
            For questions or requests regarding this policy, please contact:
          </p>
          <address className="not-italic mt-1">
            Eight Twelve Consulting LLC
            <br />
            Email: <a href="mailto:privacy@eighttwelveconsulting.com" className="text-[color-mix(in_srgb,var(--foreground)_85%,transparent)] hover:text-[var(--primary)] hover:underline focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-[var(--ring)]">privacy@eighttwelveconsulting.com</a>
          </address>
        </section>
      </div>
    </main>
  );
}
